apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-cache
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs  
  nfs:
    path: /home/funkwhale/share/gitlab/cache
    server: 192.168.1.45  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-cache
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi    
