apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-postgresql
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs  
  nfs:
    path: /mnt/nvme/kubernetes/postgresql
    server: 10.10.10.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-postgresql
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi