apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-redis
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs  
  nfs:
    path: /home/funkwhale/share/gitlab/redis
    server: 192.168.1.45
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-redis
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi    
