apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlab
  annotations:
     kubernetes.io/ingress.class: nginx
     cert-manager.io/issuer: "letsencrypt-prod"
     external-dns.alpha.kubernetes.io/hostname: gitlab.ptdev.tk
     external-dns.alpha.kubernetes.io/ttl: "120" #optional
spec:  

  tls:
     - hosts:
       - gitlab-test.ptdev.tk
       secretName:  gitlab-certificate
  rules:
    - host: gitlab.ptdev.tk
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: gitlab
              port:
                number: 80           