apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-certificate
spec:
  secretName: gitlab-certificate
  issuerRef:
    name: letsencrypt-prod
  duration: 2160h # 90d
  renewBefore: 720h # 30d before SSL will expire, renew it
  dnsNames:
    - "gitlab.ptdev.tk"